# Generated by Django 3.0.7 on 2020-06-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answers', '0003_auto_20200626_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='questions',
            name='status',
            field=models.IntegerField(choices=[(0, 'Solved'), (1, 'Unsolved')], default=0),
        ),
    ]
