# Generated by Django 3.0.7 on 2020-06-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answers', '0004_auto_20200626_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='status',
            field=models.IntegerField(choices=[(1, 'Unsolved'), (0, 'Solved')], default=0),
        ),
    ]
