# Generated by Django 3.0.7 on 2020-06-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answers', '0007_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
