# Generated by Django 3.0.7 on 2020-06-29 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answers', '0012_auto_20200628_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answersByQuestion', to='questions_answers.Questions'),
        ),
    ]
